version: '3'
networks:
  db-data-net:
    driver: bridge
services:
  mysql:
    image: my-sql:1.1
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-data-net
  pythonapp:
    image: app:1.1
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    networks:
      - db-data-net
    depends_on:
      - mysql
    restart: unless-stopped
volumes:
  db-data: